# syntax = edrevo/dockerfile-plus
# Build stage
INCLUDE+ Dockerfile-base

# Build jvm stage
FROM openjdk:16-alpine AS jvm
COPY --from=build /home/soft.gen/out/soft.generator.ts/*.jar /soft.generator.ts/
WORKDIR /soft.generator.ts
RUN jdeps --print-module-deps --multi-release 16 --ignore-missing-deps --class-path '*' -recursive soft.generator.ts-1.3.0.jar > java.modules \
 && jlink --strip-java-debug-attributes --add-modules $(cat java.modules) --output /java-generator

# Build result stage
FROM alpine
COPY --from=build /home/soft.gen/out/soft.generator.ts/*.jar /usr/share/soft.generator.ts/
COPY --from=jvm /java-generator /usr/lib/jvm/java-generator

ENTRYPOINT ["/usr/lib/jvm/java-generator/bin/java","-jar","/usr/share/soft.generator.ts/soft.generator.ts-1.3.0.jar"]
