name: Continuous Integration

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build generators
      run: make generators
    - name: Test generators
      run: make tests